from __future__ import annotations

import re

from slopcheck.rules import Finding

EMOJI = re.compile(r"[\U0001F000-\U0001FAFF☀-➿⬀-⯿]")
HEADING = re.compile(r"^#{1,6}\s")

BUZZWORDS = [
    "delve",
    "seamless",
    "leverage",
    "robust",
    "comprehensive",
    "cutting-edge",
    "state-of-the-art",
    "game-changer",
    "game-changing",
    "revolutionize",
    "revolutionary",
    "empower",
    "elevate",
    "effortlessly",
    "supercharge",
    "unleash",
    "harness the power",
    "unlock the full potential",
    "in today's fast-paced world",
    "look no further",
    "it's important to note",
    "in conclusion",
    "dive deep",
    "battle-tested",
    "blazingly fast",
]

AI_CONFESSIONS = [
    "generated with ai",
    "generated by ai",
    "written by chatgpt",
    "as an ai language model",
]

# Per-rule point caps so one obsession can't dominate the score.
CAP_EMOJI_HEADINGS = 6
CAP_BUZZWORDS = 8
CAP_EMOJI_DENSITY = 6


def check_markdown(path: str, text: str) -> list[Finding]:
    lines = text.splitlines()
    findings: list[Finding] = []
    findings += _emoji_headings(path, lines)
    findings += _buzzwords(path, lines)
    findings += _emoji_density(path, text)
    findings += _ai_confession(path, lines)
    return findings


def _emoji_headings(path: str, lines: list[str]) -> list[Finding]:
    hits = [
        (i, line)
        for i, line in enumerate(lines, 1)
        if HEADING.match(line) and EMOJI.search(line)
    ]
    if not hits:
        return []
    first_line = hits[0][0]
    points = min(len(hits) * 2, CAP_EMOJI_HEADINGS)
    return [
        Finding(
            path, first_line, "emoji-heading",
            f"{len(hits)} heading(s) decorated with emoji", points,
        )
    ]


def _buzzwords(path: str, lines: list[str]) -> list[Finding]:
    findings: list[Finding] = []
    seen: set[str] = set()
    total = 0
    for i, line in enumerate(lines, 1):
        lowered = line.lower()
        for word in BUZZWORDS:
            if word in seen or word not in lowered:
                continue
            seen.add(word)
            points = 0 if total >= CAP_BUZZWORDS else 1
            total += points
            findings.append(
                Finding(path, i, "buzzword", f'"{word}"', points)
            )
    return findings


def _emoji_density(path: str, text: str) -> list[Finding]:
    words = len(text.split())
    emoji = len(EMOJI.findall(text))
    if words < 50 or emoji == 0:
        return []
    per_100 = emoji * 100 / words
    if per_100 <= 2:
        return []
    points = min(int(per_100), CAP_EMOJI_DENSITY)
    return [
        Finding(
            path, 1, "emoji-density",
            f"{emoji} emoji in {words} words ({per_100:.1f} per 100 words)",
            points,
        )
    ]


def _ai_confession(path: str, lines: list[str]) -> list[Finding]:
    for i, line in enumerate(lines, 1):
        lowered = line.lower()
        for phrase in AI_CONFESSIONS:
            if phrase in lowered:
                return [
                    Finding(path, i, "ai-confession", f'"{phrase}"', 3)
                ]
    return []
